services:
  hai-on-hackerone:
    build:
      context: .
      dockerfile: build/Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./webserver/data:/hai-on-hackerone/webserver/data
