name: Python Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        echo "Running tests..."
        python3 -m unittest discover cli/tests
        echo "All tests passed!"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_NAME: ${{ secrets.API_NAME }}
        PROGRAM_HANDLE: ${{ secrets.PROGRAM_HANDLE }}
    - name: Generate coverage report
      run: |
        echo "Generating coverage report..."
        coverage run -m unittest discover cli/tests
        coverage xml
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_NAME: ${{ secrets.API_NAME }}
        PROGRAM_HANDLE: ${{ secrets.PROGRAM_HANDLE }}
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
