name: Python Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        pip3 install --no-cache-dir --disable-pip-version-check -r requirements.txt
    - name: Run unit tests
      run: |
        echo "Running tests..."
        cd cli/
        python3 -m unittest discover tests
        echo "All tests passed!"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_NAME: ${{ secrets.API_NAME }}
        PROGRAM_HANDLE: ${{ secrets.PROGRAM_HANDLE }}
    - name: Generate coverage report
      run: |
        echo "Generating coverage report..."
        cd cli/
        coverage run -m unittest discover tests
        coverage xml
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_NAME: ${{ secrets.API_NAME }}
        PROGRAM_HANDLE: ${{ secrets.PROGRAM_HANDLE }}
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
