name: Python Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        echo "Running tests..."
        cd cli/
        PAD=$(pwd)
        echo $PAD
        python3 -m unittest discover tests
        echo "All tests passed!"
